//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsistenciaTAlumno
    {
        public string CodAsistencia { get; set; }
        public string DniAlumno { get; set; }
        public string Estado { get; set; }
    
        public virtual Alumno TAlumno { get; set; }
        public virtual Asistencia TAsistencia { get; set; }
    }
}
