//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Docente()
        {
            this.TGradoTDocente = new HashSet<GradoDocente>();
        }
    
        public string DniDocente { get; set; }
        public string Correo { get; set; }
        public string Contrasena { get; set; }
        public string Appaterno { get; set; }
        public string Apmaterno { get; set; }
        public string Nombres { get; set; }
        public string Genero { get; set; }
        public string TelCelu { get; set; }
        public string Direccion { get; set; }
        public System.DateTime FecNacimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradoDocente> TGradoTDocente { get; set; }
    }
}
