//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectosContext : DbContext
    {
        public ProyectosContext()
            : base("name=ProyectosContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> TAlumno { get; set; }
        public virtual DbSet<Apoderado> TApoderado { get; set; }
        public virtual DbSet<Asistencia> TAsistencia { get; set; }
        public virtual DbSet<Docente> TDocente { get; set; }
        public virtual DbSet<Grado> TGrado { get; set; }
        public virtual DbSet<GradoDocente> TGradoTDocente { get; set; }
        public virtual DbSet<AsistenciaTAlumno> TAsistenciaTAlumno { get; set; }
    }
}
